/** Static zh copy for App Store screenshots (subset of App.tsx text.zh). */
export const appStoreZh = {
  appTitle: '寵物日曆',
  appSubtitle: 'Pet Calendar',
  navProBadge: 'Pro 會員',
  today: '今日',
  weight: '體重',
  history: '歷史',
  vet: '獸醫',
  more: '設定',
  remindersNav: '提醒',
  currentCat: '目前照顧',
  defaultPetName: '我的寵物',
  todayProgress: '今日完成度',
  dailyCare: '每日照顧',
  dailyCareDesc: '適合每天快速確認的照顧項目',
  abnormalRecord: '異常狀況紀錄',
  abnormalDesc: '有嘔吐、拉肚子、食慾變差、精神不好等狀況時，可以寫在這裡',
  abnormalSaved: '已記錄異常狀況',
  moreAssistant: 'AI 照護助理',
  sharedCareTodayFeedTitle: '今日照護動態',
  sharedCareTodayFeedTap: '點開查看',
  sharedCareTodayFeedCount: '則動態',
  feedMorning: '早上餵食',
  feedNight: '晚上餵食',
  litterMorning: '早上挖貓砂',
  litterNight: '晚上挖貓砂',
  pee: '今天有尿尿',
  poop: '今天有大便',
  waterCan: '補水罐 / 飲水確認',
  snack: '零食確認',
  brushHair: '梳毛確認',
  brushTeeth: '刷牙確認',
  weightTitle: '體重紀錄',
  weightDesc: '記錄體重變化，方便追蹤健康趨勢',
  latestWeight: '最新體重',
  weightChange: '近期變化',
  weightRecords: '體重列表',
  weightChart: '體重線圖',
  remindersTitle: '照護提醒',
  remindersLead: '餵食、回診、驅蟲，準時通知不漏接',
  remindersTodaySection: '今日提醒',
  assistantTitle: 'AI 照護助理',
  assistantLead: '依紀錄整理趨勢與提醒；僅供參考，不能取代獸醫。',
  assistantQuickSummary: '今日快覽',
  assistantCareReminders: '照護提醒（1～3 點）',
  assistantAskPlaceholder: '例如：這週喝水感覺怎樣？體重需要多留意嗎？',
  assistantSend: '送出',
  aiAnalysisCardTitle: '快速照護分析',
  vetTitle: '進階獸醫報告',
  vetLead: '整理照護紀錄給獸醫參考，非醫療診斷。',
  vetPreset30: '最近 30 天',
  vetAiSection: 'AI 整理重點',
  vetExportPdf: '匯出 PDF',
} as const;

export type AppStoreLabelKey = keyof typeof appStoreZh;
